name: Auto Package

on:
  schedule:
    - cron: "0 0 * * 3"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 100
      - name: Empty Commit
        run: |
          git config --global user.name 'Nitrak'
          git config --global user.email 'nitrak@wow.com'
          git commit --allow-empty -am "Empty commit"
          git push --force
          echo "sha_short=$(git rev-parse HEAD)" >> "$GITHUB_ENV"
      - name: Export LATEST_TAG
        run: |
          echo "LATEST_TAG=$(curl -qsSL \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "${{ github.api_url }}/repos/${{ github.repository }}/releases/latest" \
          | jq -r .tag_name | sed 's/\(-.*\)//')" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.LATEST_TAG }}-${{ github.run_number }}
          release_name: Vocal Raid Assistant
          commitish: ${{ env.sha_short }}
          body: |
          draft: false
          prerelease: false
